In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C:/Users/Владислав/housing-price-prediction/data/processed/train_cleaned.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1460 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  MasVnrType     588 non-null    object
 24  MasVnrArea     1460 non-null   float64
 25  ExterQual      1460 non-null   object
 26  ExterCond      1460 non-null   object
 27  Foundation     1460 non-null   object
 28  BsmtQual       1460 non-null   object
 29  BsmtCond       1460 non-null   object
 30  BsmtExposure   1460 non-null   object
 31  BsmtFinType1   1460 non-null   object
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1460 non-null   object
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   object
 38  HeatingQC      1460 non-null   object
 39  CentralAir     1460 non-null   object
 40  Electrical     1460 non-null   object
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   object
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   object
 54  Fireplaces     1460 non-null   int64
 55  FireplaceQu    1460 non-null   object
 56  GarageType     1460 non-null   object
 57  GarageYrBlt    1460 non-null   float64
 58  GarageFinish   1460 non-null   object
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1460 non-null   object
 62  GarageCond     1460 non-null   object
 63  PavedDrive     1460 non-null   object
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  MiscVal        1460 non-null   int64
 71  MoSold         1460 non-null   int64
 72  YrSold         1460 non-null   int64
 73  SaleType       1460 non-null   object
 74  SaleCondition  1460 non-null   object
 75  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(39)
memory usage: 867.0+ KB

In [3]:
# Общая площадь подвала
df['TotalBsmtSF'] = df['BsmtFinSF1'] + df['BsmtFinSF2'] + df['BsmtUnfSF']

In [4]:
# Площадь законченной части
df['TotalFinishedBsmt'] = df['BsmtFinSF1'] + df['BsmtFinSF2']
df['FinishedBsmtRatio'] = np.where(
    df['TotalBsmtSF'] == 0,
    0,
    df['TotalFinishedBsmt'] / df['TotalBsmtSF']
)
df['FinishedBsmtRatio']

0       0.824766
1       0.774960
2       0.528261
3       0.285714
4       0.572052
          ...
1455    0.000000
1456    0.618029
1457    0.238715
1458    1.000000
1459    0.891720
Name: FinishedBsmtRatio, Length: 1460, dtype: float64

In [5]:
# Общее количество ванных комнат
df['TotalBathrooms'] = (
    df['BsmtFullBath'] 
    + df['FullBath'] 
    + 0.5 * df['BsmtHalfBath'] 
    + df['HalfBath']
)

In [6]:
# Общая площадь крыльца
df['TotalPorchSF'] = (
    df['EnclosedPorch']
    + df['3SsnPorch']
    + df['ScreenPorch']
)

In [7]:
# Вывод новых объясняющих переменных
df[['TotalBathrooms', 'FinishedBsmtRatio', 'TotalBsmtSF', 'TotalPorchSF']].head()

   TotalBathrooms  FinishedBsmtRatio  TotalBsmtSF  TotalPorchSF
0             4.0           0.824766          856             0
1             2.5           0.774960         1262             0
2             4.0           0.528261          920             0
3             2.0           0.285714          756           272
4             4.0           0.572052         1145             0

In [8]:
# Возраст дома
df['HouseAge'] = df['YrSold'] - df['YearBuilt']

# Возраст с момента реконструкий/добавлений
df['RemodelAge'] = df['YrSold'] - df['YearRemodAdd']

# Общая площадь дома
df['TotalHouseSF'] = df['TotalBsmtSF'] + df['GrLivArea']

# Общая площадь крыльца
df['TotalHouseSF'] = (
    df['OpenPorchSF']
    + df['EnclosedPorch']
    + df['3SsnPorch']
    + df['ScreenPorch']
)

# Наличие второго этажа
df['Has2edFloor'] = (df['2ndFlrSF'] > 0).astype(int)

# Наличие гаража
df['HasGarage'] = (df['GarageArea'] > 0).astype(int)

In [9]:
df[['HouseAge', 'RemodelAge', 'TotalHouseSF', 'TotalHouseSF', 'Has2edFloor', 'HasGarage','TotalBathrooms', 'FinishedBsmtRatio', 'TotalBsmtSF', 'TotalPorchSF']].head()

,HouseAge,RemodelAge,TotalHouseSF,TotalHouseSF,Has2edFloor,HasGarage,TotalBathrooms,FinishedBsmtRatio,TotalBsmtSF,TotalPorchSF
0,5,5,61,61,1,1,4.0,0.824766,856,0
1,31,31,0,0,0,1,2.5,0.774960,1262,0
2,7,6,42,42,1,1,4.0,0.528261,920,0
3,91,36,307,307,1,1,2.0,0.285714,756,272
4,8,8,84,84,1,1,4.0,0.572052,1145,0

In [10]:
df.to_csv("C:/Users/Владислав/housing-price-prediction/data/processed/train_fe.csv")