In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_clean = pd.read_csv("C:/Users/Владислав/housing-price-prediction/data/processed/train_cleaned.csv")
df_feature = pd.read_csv("C:/Users/Владислав/housing-price-prediction/data/processed/train_fe.csv")
df_clean.head(5)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [3]:
df_feature.head(5)

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,SalePrice,TotalFinishedBsmt,FinishedBsmtRatio,TotalBathrooms,TotalPorchSF,HouseAge,RemodelAge,TotalHouseSF,Has2edFloor,HasGarage
0,0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,208500,706,0.824766,4.0,0,5,5,61,1,1
1,1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,181500,978,0.774960,2.5,0,31,31,0,0,1
2,2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,223500,486,0.528261,4.0,0,7,6,42,1,1
3,3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,140000,216,0.285714,2.0,272,91,36,307,1,1
4,4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,250000,655,0.572052,4.0,0,8,8,84,1,1

In [4]:
X_clean = df_clean.drop("SalePrice", axis=1)
y_clean = df_clean["SalePrice"]

In [5]:
X_fe= df_feature.drop("SalePrice", axis=1)
y_fe = df_feature["SalePrice"]

In [6]:
from sklearn.model_selection import train_test_split

Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_clean, y_clean, test_size=0.2, random_state=42
)

In [7]:
categorical_cols = Xc_train.select_dtypes(include='object').columns
numerical_cols = Xc_train.select_dtypes(exclude='object').columns

In [8]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [10]:
Xc_train_cat = encoder.fit_transform(Xc_train[categorical_cols])
Xc_test_cat = encoder.transform(Xc_test[categorical_cols])

Xc_train_num = Xc_train[numerical_cols].to_numpy()
Xc_test_num = Xc_test[numerical_cols].to_numpy()

print(Xc_train_num.shape)
print(Xc_train_cat.shape)
print(Xc_test_num.shape)
print(Xc_test_cat.shape)

(1168, 36)
(1168, 247)
(292, 36)
(292, 247)

In [11]:
Xc_train_final = np.hstack([Xc_train_num, Xc_train_cat])
Xc_test_final = np.hstack([Xc_test_num, Xc_test_cat])

In [12]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(Xc_train_final, yc_train)

LinearRegression()

In [13]:
yc_pred = model.predict(Xc_test_final)

In [14]:
from sklearn.metrics import mean_squared_error

rmse_clean = np.sqrt(mean_squared_error(yc_test, yc_pred))
print("RMSE clean: ", rmse_clean)

RMSE clean:  29611.98726728166

In [15]:
# То же самое для X_fe и y_fe
Xfe_train, Xfe_test, yfe_train, yfe_test = train_test_split(
    X_fe, y_fe, test_size =0.2, random_state=42
)

In [16]:
categorical_cols = Xfe_train.select_dtypes(include='object').columns
numerical_cols = Xfe_train.select_dtypes(exclude='object').columns

In [17]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [18]:
Xfe_train_cat = encoder.fit_transform(Xfe_train[categorical_cols])
Xfe_test_cat = encoder.transform(Xfe_test[categorical_cols])

Xfe_train_num = Xfe_train[numerical_cols].to_numpy()
Xfe_test_num = Xfe_test[numerical_cols].to_numpy()

print(Xfe_train_num.shape)
print(Xfe_train_cat.shape)
print(Xfe_test_num.shape)
print(Xfe_test_cat.shape)

(1168, 46)
(1168, 247)
(292, 46)
(292, 247)

In [19]:
Xfe_train_final = np.hstack([Xfe_train_num, Xfe_train_cat])
Xfe_test_final = np.hstack([Xfe_test_num, Xfe_test_cat])

print(np.isnan(Xfe_train_final).sum())
print(np.isinf(Xfe_train_final).sum())

print(np.isnan(Xfe_test_final).sum())
print(np.isinf(Xfe_test_final).sum())

0
0
0
0

In [20]:
model = LinearRegression()
model.fit(Xfe_train_final, yfe_train)

LinearRegression()

In [21]:
yfe_pred = model.predict(Xfe_test_final)

In [22]:
rmse_fe = np.sqrt(mean_squared_error(yfe_test, yfe_pred))
print("RMSE clean: ", rmse_fe)

RMSE clean:  29552.250601904627

In [23]:
print(rmse_clean)
print(rmse_fe)

29611.98726728166
29552.250601904627

In [47]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

Xfe_train_num_scaled = scaler.fit_transform(Xfe_train_num)
Xfe_test_num_scaled = scaler.transform(Xfe_test_num)

Xfe_train_final_scaled = np.hstack([Xfe_train_num_scaled, Xfe_train_cat])
Xfe_test_final_scaled = np.hstack([Xfe_test_num_scaled, Xfe_test_cat])

In [48]:
from sklearn.metrics import mean_squared_error
import numpy as np

def evaluate_model(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    return rmse

In [52]:
models_no_scaling = {
    "LinearRegression": LinearRegression(),
    "RandomForest": RandomForestRegressor(random_state=42)
}

models_with_scaling = {
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.001, max_iter=10000)
}

In [50]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor

models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.001),
    "RandomForest": RandomForestRegressor(random_state=42)
}

In [53]:
results = {}

for name, model in models_no_scaling.items():
    rmse = evaluate_model(model, Xfe_train_final, yfe_train, Xfe_test_final, yfe_test)
    results[name] = rmse

for name, model in models_with_scaling.items():
    rmse = evaluate_model(model, Xfe_train_final_scaled, yfe_train, Xfe_test_final_scaled, yfe_test)
    results[name] = rmse

C:\Users\Владислав\housing-price-prediction\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.224e+11, tolerance: 6.967e+08
  model = cd_fast.enet_coordinate_descent(

In [54]:
import pandas as pd

results_df = pd.DataFrame(list(results.items()), columns=["Model", "RMSE"])
results_df = results_df.sort_values(by="RMSE")
results_df

              Model          RMSE
1      RandomForest  28251.319133
3             Lasso  28263.491197
2             Ridge  29224.234252
0  LinearRegression  29552.250602